# Lesson 2 Practical Application

1. Data science is the practice of drawing useful conclusion from large sets of data using computation as a primary tool. In the Air Force, data science can be used to identify significant trends in data surrounding all kinds of subjects.

2. The three focus areas of the course are exploration, inference, and prediction.

In [1]:
2+2

4

In [2]:
2*8

16

In [3]:
8/3

2.6666666666666665

In [109]:
print('Joe Belina \U0001F44D')


Joe Belina 👍


6. 
It is highly unlikely that an increase in ice cream sales causes violent crime or that violent crime causes an increase in ice cream sales. It is much more likely that the time of year is a confounding variable for both of these results. When it comes summertime, ice cream sales are likely to increase along with violent crime. As such, both results do not cause one another but are the results of a third variable.

7. An observational study is limited to what its name implies: observation only. In an observational study, no variables are deliberately changed in order to observe its effect on what is being studied, but the subject is only carefully studied under its normal conditions. In contrast, experiments revolve around changing the independent variables and observing how the dependent variable responds.

# Lesson 3 Practical Application

In [11]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

In [4]:
sec_in_june = 30 * 24 * 60 * 60

In [9]:
sec_in_june

2592000

In [10]:
sec_in_july = 31 * 24 * 60 * 60

In [6]:
sec_in_aug = (13 * 24 * 60 * 60) + (9.5 * 60 *60)

In [11]:
sec_in_frame = (29.5/30)*sec_in_june + sec_in_july + sec_in_aug

In [12]:
sec_in_frame

6384600.0

In [33]:
pop = Table.read_table('world_population.csv')
pop

Population
2557628654
2594939877
2636772306
2682053389
2730228104
2782098943
2835299673
2891349717
2948137248
3000716593
... (56 rows omitted)

In [31]:
poparray = pop.column('Population')
poparray

array([2557628654, 2594939877, 2636772306, 2682053389, 2730228104,
       2782098943, 2835299673, 2891349717, 2948137248, 3000716593,
       3043001508, 3083966929, 3140093217, 3209827882, 3281201306,
       3350425793, 3420677923, 3490333715, 3562313822, 3637159050,
       3712697742, 3790326948, 3866568653, 3942096442, 4016608813,
       4089083233, 4160185010, 4232084578, 4304105753, 4379013942,
       4451362735, 4534410125, 4614566561, 4695736743, 4774569391,
       4856462699, 4940571232, 5027200492, 5114557167, 5201440110,
       5288955934, 5371585922, 5456136278, 5538268316, 5618682132,
       5699202985, 5779440593, 5857972543, 5935213248, 6012074922,
       6088571383, 6165219247, 6242016348, 6318590956, 6395699509,
       6473044732, 6551263534, 6629913759, 6709049780, 6788214394,
       6866332358, 6944055583, 7022349283, 7101027895, 7178722893,
       7256490011], dtype=int64)

In [43]:
poparray.item(65)

7256490011

In [28]:
pop_growth = max(poparray) - min(poparray)
pop_growth

4698861357

In [47]:
avg_growth = (((max(poparray)/min(poparray))**(1/65))-1)*100
avg_growth

1.617270380658975

In [127]:
Titanic = Table.read_table("https://raw.githubusercontent.com/oikobill/Kaggle/master/Titanic/data/train.csv")
Titanic

PassengerId | Survived | Pclass | Name                                                | Sex    | Age  | SibSp | Parch | Ticket           | Fare    | Cabin | Embarked
1           | 0        | 3      | Braund, Mr. Owen Harris                             | male   | 22   | 1     | 0     | A/5 21171        | 7.25    | nan   | S
2           | 1        | 1      | Cumings, Mrs. John Bradley (Florence Briggs Thayer) | female | 38   | 1     | 0     | PC 17599         | 71.2833 | C85   | C
3           | 1        | 3      | Heikkinen, Miss. Laina                              | female | 26   | 0     | 0     | STON/O2. 3101282 | 7.925   | nan   | S
4           | 1        | 1      | Futrelle, Mrs. Jacques Heath (Lily May Peel)        | female | 35   | 1     | 0     | 113803           | 53.1    | C123  | S
5           | 0        | 3      | Allen, Mr. William Henry                            | male   | 35   | 0     | 0     | 373450           | 8.05    | nan   | S
6           | 0        | 3      | Moran, Mr. James                                    | male   | nan  | 0     | 0     | 330877           | 8.4583  | nan   | Q
7           | 0        | 1      | McCarthy, Mr. Timothy J                             | male   | 54   | 0     | 0     | 17463            | 51.8625 | E46   | S
8           | 0        | 3      | Palsson, Master. Gosta Leonard                      | male   | 2    | 3     | 1     | 349909           | 21.075  | nan   | S
9           | 1        | 3      | Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   | female | 27   | 0     | 2     | 347742           | 11.1333 | nan   | S
10          | 1        | 2      | Nasser, Mrs. Nicholas (Adele Achem)                 | female | 14   | 1     | 0     | 237736           | 30.0708 | nan   | C
... (881 rows omitted)

In [128]:
Titanic.relabel("Pclass","passenger_class")

PassengerId | Survived | passenger_class | Name                                                | Sex    | Age  | SibSp | Parch | Ticket           | Fare    | Cabin | Embarked
1           | 0        | 3               | Braund, Mr. Owen Harris                             | male   | 22   | 1     | 0     | A/5 21171        | 7.25    | nan   | S
2           | 1        | 1               | Cumings, Mrs. John Bradley (Florence Briggs Thayer) | female | 38   | 1     | 0     | PC 17599         | 71.2833 | C85   | C
3           | 1        | 3               | Heikkinen, Miss. Laina                              | female | 26   | 0     | 0     | STON/O2. 3101282 | 7.925   | nan   | S
4           | 1        | 1               | Futrelle, Mrs. Jacques Heath (Lily May Peel)        | female | 35   | 1     | 0     | 113803           | 53.1    | C123  | S
5           | 0        | 3               | Allen, Mr. William Henry                            | male   | 35   | 0     | 0     | 373450           | 8.05    | nan   | S
6           | 0        | 3               | Moran, Mr. James                                    | male   | nan  | 0     | 0     | 330877           | 8.4583  | nan   | Q
7           | 0        | 1               | McCarthy, Mr. Timothy J                             | male   | 54   | 0     | 0     | 17463            | 51.8625 | E46   | S
8           | 0        | 3               | Palsson, Master. Gosta Leonard                      | male   | 2    | 3     | 1     | 349909           | 21.075  | nan   | S
9           | 1        | 3               | Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   | female | 27   | 0     | 2     | 347742           | 11.1333 | nan   | S
10          | 1        | 2               | Nasser, Mrs. Nicholas (Adele Achem)                 | female | 14   | 1     | 0     | 237736           | 30.0708 | nan   | C
... (881 rows omitted)

In [129]:
Titanic = Titanic.with_column("family_size",Titanic.column("SibSp")+Titanic.column("Parch"))

In [73]:
Pclasses = Titanic.group(Titanic.column("passenger_class")[Titanic.column("family_size")])
Pclasses
Pclasses.bar("group","count")

In [117]:
Titanic.sort("Age").show(5)

# Lesson 4 Practical Application

In [29]:
Name = "Joe Belina"
Age = 20
Hometown = "Owatonna, Minnesota"
print("I am",Name,". I am",Age,"years old. I'm from ",Hometown,".")

I am Joe Belina . I am 20 years old. I'm from  Owatonna, Minnesota .


In [14]:
Name.lower()

'joe belina'

In [15]:
Name.title()

'Joe Belina'

In [26]:
string = "I am Joe Belina. I am 20 years old. I'm from Owatonna, Minnesota."
string.replace("I am","He is").replace("I'm","He's")

"He is Joe Belina. He is 20 years old. He's from Owatonna, Minnesota."

In [32]:
len(string)>(40+Age)

True

# Lesson 5 Practical Application

In [3]:
#1
string = make_array("Joe","Belina","Minnesota","Blue")
string

array(['Joe', 'Belina', 'Minnesota', 'Blue'], dtype='<U9')

In [4]:
#1a
np.char.upper(string)

array(['JOE', 'BELINA', 'MINNESOTA', 'BLUE'], dtype='<U9')

In [5]:
#1b
np.char.count(string,"a")

array([0, 1, 1, 0])

In [8]:
#2
array = np.arange(1,49,4)
array

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

In [10]:
#2a
np.sum(array)

276

In [11]:
#2b
np.prod(array)

616159193

In [12]:
np.log(array)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])